openapi: 3.0.3
info:
  title: Vigilia
  description: API for the Vigilia Service
  version: 1.0.0

servers:
  - url: 'http://localhost:54913/api'

paths:
  /index:
    post:
      summary: Index new files
      description: Index new files
      operationId: IndexFiles
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
      responses:
        '200':
          description: Indexing successful
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /search:
    post:
      summary: Search for files
      description: Search for files
      operationId: SearchFiles
      parameters:
        - name: pageNumber
          in: query
          description: Page number
          required: false
          schema:
            default: 0
            type: integer
            format: int32
        - name: pageSize
          in: query
          description: Page size
          required: false
          schema:
            default: 20
            type: integer
            format: int32
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: Search successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/searchResult'
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /system/media-types:
    get:
      summary: Get media types
      description: Get media types
      operationId: GetMediaTypes
      responses:
        '200':
          description: Media types retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/supportedMediaTypes'
        '500':
          description: Internal server error
  /system/version:
    get:
      summary: Get the version of the core
      description: Get the version of the core
      operationId: GetVersion
      responses:
        '200':
          description: Version retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CoreVersion'

components:
  schemas:
    searchResult:
      type: object
      properties:
        path:
          type: string
        text:
          type: string
        score:
          type: number
          format: double
    supportedMediaTypes:
      type: object
      required:
        - document
        - image
        - video
        - audio
      properties:
        document:
          type: array
          items:
            type: string
        image:
          type: array
          items:
            type: string
        video:
          type: array
          items:
            type: string
        audio:
          type: array
          items:
            type: string
    CoreVersion:
      type: object
      properties:
        serviceVersion:
          type: string
        apiVersion:
          type: string

