#!/bin/sh

set -e

echo "Running postinst for vig core with $1"
if  [ "$1" = configure ]; then
  # creating a link, so the application can be called from the command line
  ln -sf /opt/vig-core/bin/Vigilia-Core /bin/vig-core
fi

exit 0
