name: Build with Maven

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: "The project version to build. It should be equal to the version in the pom.xml file."

jobs:
  verify:
    name: Verify Project before Build
    uses: ./.github/workflows/verify.yaml

  # Windows does not allow text in versions. See requirements:
  # https://learn.microsoft.com/en-gb/windows/win32/msi/productversion
  win-version-string:
    name: Create Version String for Windows
    runs-on: ubuntu-latest
    outputs:
      winVersion: ${{ steps.step1.outputs.winVersion }}
    steps:
      - id: step1
        name: Create Version String for Windows and write it to Output
        run: |
          winVersion=$(echo "${{ inputs.version }}" | grep -oP "\d+(\.\d+)+")
          echo "${winVersion}"
          echo "winVersion=${winVersion}" >> "$GITHUB_OUTPUT"

  build:
    name: Build
    needs: [ verify, win-version-string ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4.2.2
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Build and Package
        run: |
          ./mvnw versions:set -DnewVersion="${{ inputs.version }}"
          ./mvnw versions:commit
          
          ./mvnw --batch-mode --update-snapshots package
          ./mvnw --batch-mode jpackage:jpackage -pl core,cli,fx-gui
      - name: Upload Core
        uses: actions/upload-artifact@v4
        with:
          name: core-deb
          path: ./core/target/vig-core_${{ inputs.version }}_amd64.deb
          retention-days: 1
          overwrite: true
          if-no-files-found: error
      - name: Upload CLI
        uses: actions/upload-artifact@v4
        with:
          name: cli-deb
          path: ./cli/target/vig_${{ inputs.version }}_amd64.deb
          retention-days: 1
          overwrite: true
          if-no-files-found: error
      - name: Upload FX GUI
        uses: actions/upload-artifact@v4
        with:
          name: fx-gui-deb
          path: ./fx-gui/target/vig-gui_${{ inputs.version }}_amd64.deb
          retention-days: 1
          overwrite: true
          if-no-files-found: error
