name: Build and Release on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  create-version-string:
    name: "Create Version String from Tag"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.step1.outputs.version }}
    steps:
      - id: step1
        run: |
          version=$(echo "${{ github.ref_name }}" | cut -c 2-)
          echo "${version}"
          echo "version=${version}" >> "$GITHUB_OUTPUT"

  build:
    uses: ./.github/workflows/build.yaml
    with:
      version: ${{ needs.create-version-string.outputs.version }}
    secrets: inherit

  release:
    needs: build
    uses: ./.github/workflows/release.yaml
    with:
      tag: ${{ github.ref_name }}
      version: ${{ needs.create-version-string.outputs.version }}
      prerelease: false
    secrets: inherit
