name: Verify

on:
  push:
  workflow_call:

jobs:
  verify:
    name: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Verify with Maven
        run: ./mvnw --batch-mode --update-snapshots verify
